#ifndef ADDER32APPROXFIFTYPERCENTPOWERLIBRARY_H
#define ADDER32APPROXFIFTYPERCENTPOWERLIBRARY_H

/**
 * @brief This is the auto-generated file given by the hardware team.
 */
void AND2_X1 ( int A1, int A2, int* ZN);
void AND2_X2 ( int A1, int A2, int* ZN);
void AND2_X4 ( int A1, int A2, int* ZN);
void AND3_X1 ( int A1, int A2, int A3, int* ZN);
void AND3_X2 ( int A1, int A2, int A3, int* ZN);
void AND3_X4 ( int A1, int A2, int A3, int* ZN);
void AND4_X1 ( int A1, int A2, int A3, int A4, int* ZN);
void AND4_X2 ( int A1, int A2, int A3, int A4, int* ZN);
void AND4_X4 ( int A1, int A2, int A3, int A4, int* ZN);
void ANTENNA_X1 ( int A);
void AOI211_X1 ( int A, int B, int C1, int C2, int* ZN);
void AOI211_X2 ( int A, int B, int C1, int C2, int* ZN);
void AOI211_X4 ( int A, int B, int C1, int C2, int* ZN);
void AOI21_X1 ( int A, int B1, int B2, int* ZN);
void AOI21_X2 ( int A, int B1, int B2, int* ZN);
void AOI21_X4 ( int A, int B1, int B2, int* ZN);
void AOI221_X1 ( int A, int B1, int B2, int C1, int C2, int* ZN);
void AOI221_X2 ( int A, int B1, int B2, int C1, int C2, int* ZN);
void AOI221_X4 ( int A, int B1, int B2, int C1, int C2, int* ZN);
void AOI222_X1 ( int A1, int A2, int B1, int B2, int C1, int C2, int* ZN);
void AOI222_X2 ( int A1, int A2, int B1, int B2, int C1, int C2, int* ZN);
void AOI222_X4 ( int A1, int A2, int B1, int B2, int C1, int C2, int* ZN);
void AOI22_X1 ( int A1, int A2, int B1, int B2, int* ZN);
void AOI22_X2 ( int A1, int A2, int B1, int B2, int* ZN);
void AOI22_X4 ( int A1, int A2, int B1, int B2, int* ZN);
void BUF_X1 ( int A, int* Z);
void BUF_X16 ( int A, int* Z);
void BUF_X2 ( int A, int* Z);
void BUF_X32 ( int A, int* Z);
void BUF_X4 ( int A, int* Z);
void BUF_X8 ( int A, int* Z);
void CLKBUF_X1 ( int A, int* Z);
void CLKBUF_X2 ( int A, int* Z);
void CLKBUF_X3 ( int A, int* Z);
void DFFRS_X1 ( int D, int RN, int SN, int CK, int* Q, int* QN);
void DFFRS_X2 ( int D, int RN, int SN, int CK, int* Q, int* QN);
void DFFR_X1 ( int D, int RN, int CK, int* Q, int* QN);
void DFFR_X2 ( int D, int RN, int CK, int* Q, int* QN);
void DFFS_X1 ( int D, int SN, int CK, int* Q, int* QN);
void DFFS_X2 ( int D, int SN, int CK, int* Q, int* QN);
void DFF_X1 ( int D, int CK, int* Q, int* QN);
void DFF_X2 ( int D, int CK, int* Q, int* QN);
void FA_X1 ( int A, int B, int CI, int* CO, int* S);
void HA_X1 ( int A, int B, int* CO, int* S);
void INV_X1 ( int A, int* ZN);
void INV_X16 ( int A, int* ZN);
void INV_X2 ( int A, int* ZN);
void INV_X32 ( int A, int* ZN);
void INV_X4 ( int A, int* ZN);
void INV_X8 ( int A, int* ZN);
void LOGIC0_X1 ( int* Z);
void LOGIC1_X1 ( int* Z);
void MUX2_X1 ( int A, int B, int S, int* Z);
void MUX2_X2 ( int A, int B, int S, int* Z);
void NAND2_X1 ( int A1, int A2, int* ZN);
void NAND2_X2 ( int A1, int A2, int* ZN);
void NAND2_X4 ( int A1, int A2, int* ZN);
void NAND3_X1 ( int A1, int A2, int A3, int* ZN);
void NAND3_X2 ( int A1, int A2, int A3, int* ZN);
void NAND3_X4 ( int A1, int A2, int A3, int* ZN);
void NAND4_X1 ( int A1, int A2, int A3, int A4, int* ZN);
void NAND4_X2 ( int A1, int A2, int A3, int A4, int* ZN);
void NAND4_X4 ( int A1, int A2, int A3, int A4, int* ZN);
void NOR2_X1 ( int A1, int A2, int* ZN);
void NOR2_X2 ( int A1, int A2, int* ZN);
void NOR2_X4 ( int A1, int A2, int* ZN);
void NOR3_X1 ( int A1, int A2, int A3, int* ZN);
void NOR3_X2 ( int A1, int A2, int A3, int* ZN);
void NOR3_X4 ( int A1, int A2, int A3, int* ZN);
void NOR4_X1 ( int A1, int A2, int A3, int A4, int* ZN);
void NOR4_X2 ( int A1, int A2, int A3, int A4, int* ZN);
void NOR4_X4 ( int A1, int A2, int A3, int A4, int* ZN);
void OAI211_X1 ( int A, int B, int C1, int C2, int* ZN);
void OAI211_X2 ( int A, int B, int C1, int C2, int* ZN);
void OAI211_X4 ( int A, int B, int C1, int C2, int* ZN);
void OAI21_X1 ( int A, int B1, int B2, int* ZN);
void OAI21_X2 ( int A, int B1, int B2, int* ZN);
void OAI21_X4 ( int A, int B1, int B2, int* ZN);
void OAI221_X1 ( int A, int B1, int B2, int C1, int C2, int* ZN);
void OAI221_X2 ( int A, int B1, int B2, int C1, int C2, int* ZN);
void OAI221_X4 ( int A, int B1, int B2, int C1, int C2, int* ZN);
void OAI222_X1 ( int A1, int A2, int B1, int B2, int C1, int C2, int* ZN);
void OAI222_X2 ( int A1, int A2, int B1, int B2, int C1, int C2, int* ZN);
void OAI222_X4 ( int A1, int A2, int B1, int B2, int C1, int C2, int* ZN);
void OAI22_X1 ( int A1, int A2, int B1, int B2, int* ZN);
void OAI22_X2 ( int A1, int A2, int B1, int B2, int* ZN);
void OAI22_X4 ( int A1, int A2, int B1, int B2, int* ZN);
void OAI33_X1 ( int A1, int A2, int A3, int B1, int B2, int B3, int* ZN);
void OR2_X1 ( int A1, int A2, int* ZN);
void OR2_X2 ( int A1, int A2, int* ZN);
void OR2_X4 ( int A1, int A2, int* ZN);
void OR3_X1 ( int A1, int A2, int A3, int* ZN);
void OR3_X2 ( int A1, int A2, int A3, int* ZN);
void OR3_X4 ( int A1, int A2, int A3, int* ZN);
void OR4_X1 ( int A1, int A2, int A3, int A4, int* ZN);
void OR4_X2 ( int A1, int A2, int A3, int A4, int* ZN);
void OR4_X4 ( int A1, int A2, int A3, int A4, int* ZN);
void SDFFRS_X1 ( int D, int RN, int SE, int SI, int SN, int CK, int* Q, int* QN);
void SDFFRS_X2 ( int D, int RN, int SE, int SI, int SN, int CK, int* Q, int* QN);
void SDFFR_X1 ( int D, int RN, int SE, int SI, int CK, int* Q, int* QN);
void SDFFR_X2 ( int D, int RN, int SE, int SI, int CK, int* Q, int* QN);
void SDFFS_X1 ( int D, int SE, int SI, int SN, int CK, int* Q, int* QN);
void SDFFS_X2 ( int D, int SE, int SI, int SN, int CK, int* Q, int* QN);
void SDFF_X1 ( int D, int SE, int SI, int CK, int* Q, int* QN);
void SDFF_X2 ( int D, int SE, int SI, int CK, int* Q, int* QN);
void XNOR2_X1 ( int A, int B, int* ZN);
void XNOR2_X2 ( int A, int B, int* ZN);
void XOR2_X1 ( int A, int B, int* Z);
void XOR2_X2 ( int A, int B, int* Z);
#endif